# Generated by Django 4.0.2 on 2022-04-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='haircolor',
            field=models.CharField(default='brown', max_length=20),
        ),
        migrations.AddField(
            model_name='people',
            name='isMarried',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(default='Unknwon', max_length=100),
        ),
    ]
