# Generated by Django 4.0.2 on 2022-04-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_people_haircolor_people_ismarried_people_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='people',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='people',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
